using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DelegatesAndEvents
{
    //public delegate int WorkPerformedHandler(object sender, WorkPerformedEventArgs e);
    // public delegate int WorkPerformedHandler(hours, WorkType);


    class Program
    {
        public delegate int BizRulesDelegate(int x, int y);

        static void Main(string[] args)
        {
            var custs = new List<Customer>
            {
                new Customer {City = "Phoenix", FirstName = "John", LastName = "Doe", ID = 1},
                new Customer {City = "Phoenix", FirstName = "Jane", LastName = "Doe", ID = 500},
                new Customer {City = "Seattle", FirstName = "Suki", LastName = "Pizzoro", ID = 3},
                new Customer {City = "New York", FirstName = "Michelle", LastName = "Smith", ID = 4}
            };

            var phCusts = custs
                .Where(c => c.City == "Phoenix" && c.ID < 500)
                .OrderBy(c => c.FirstName);

            foreach (var cust in phCusts)
            {
                Console.WriteLine(cust.FirstName);
            }

            var data = new ProcessData();
            BizRulesDelegate addDel = (x, y) => x + y;
            BizRulesDelegate multDel = (x, y) => x * y;
            Action<int, int> myAction = (x, y) => Console.WriteLine(x + y);
            Action<int, int> myMultAction = (x, y) => Console.WriteLine(x * y);
            //data.ProcessAction(2, 3, myAction);

            Func<int, int, int> funcAddDel = (x, y) => x + y;
            Func<int, int, int> funcMultDel = (x, y) => x * y;
            data.ProcessFunc(3, 2, funcAddDel);



            var worker = new Worker();
            worker.WorkPerformed += delegate (object sender, WorkPerformedEventArgs e)
            { Console.WriteLine($"Hours worked: {e.Hours}; Work Type: {e.WorkType}"); };
            worker.WorkCompleted += (s, e) => Console.WriteLine("Worker is done.");
            worker.DoWork(8, Worker.WorkType.GenerateReports);

            Console.ReadLine();

            //WorkPerformedHandler del1 = new WorkPerformedHandler(WorkPerformed1);
            //WorkPerformedHandler del2 = new WorkPerformedHandler(WorkPerformed2);
            //WorkPerformedHandler del3 = new WorkPerformedHandler(WorkPerformed3);

            //del1 += del2 + del3;

            //int finalHours = del1(10, WorkType.GenerateReports);
            //Console.WriteLine(finalHours);
        }

        //private static void Worker_WorkPerformed(object sender, WorkPerformedEventArgs e) //auto-generated by += tab tab
        //{
        //    Console.WriteLine($"Hours worked: {e.Hours}; Work Type: {e.WorkType}");
        //}

        //static void Worker_WorkPerformed(object sender, WorkPerformedEventArgs e)
        //{
        //    Console.WriteLine($"Hours worked: {e.Hours}; Work Type: {e.WorkType}");
        //}

        //static void Worker_WorkCompleted(object sender, EventArgs e)
        //{
        //    Console.WriteLine("Worker is done.");
        //}

        //        static void DoWork(WorkPerformedHandler del)
        //        {
        //            del(5, WorkType.Golf);
        //        }

        //        static int WorkPerformed1(int hours, WorkType workType)
        //        {
        //            Console.WriteLine("WorkPerformed1 called " + hours.ToString());
        //            return hours + 1;
        //        }

        //        static int WorkPerformed2(int hours, WorkType workType)
        //        {
        //            Console.WriteLine("WorkPerformed2 called " + hours.ToString());
        //            return hours + 2;
        //        }

        //        static int WorkPerformed3(int hours, WorkType workType)
        //        {
        //            Console.WriteLine("WorkPerformed3 called " + hours.ToString());
        //            return hours + 3;
        //        }
        //    }
    }
}
